name: PHP 8.4

permissions:
    packages: write

on:
    push:
        branches:
            - 'main'
        tags:
            - 'v*.*.*'
        paths:
            - 'php8.4/**'
            - '.github/workflows/php8.4.yml'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: |
                        ghcr.io/thedevs-cz/php
                    tags: |
                        8.4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GHCR
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: ./php8.4
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    platforms: linux/amd64,linux/arm64
                    cache-from: type=gha, scope=${{ github.workflow }}
                    cache-to: type=gha, scope=${{ github.workflow }}
